services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 46
    
  client:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    working_dir: /app/client
    command: ["ng", "serve", "--host", "0.0.0.0"]
    depends_on:
      - app
  
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
