services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    mem_limit: 4g
  
  client:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    working_dir: /app/client
    command: ["ng", "serve", "--host", "0.0.0.0"]
    depends_on:
      - app
    mem_limit: 4g
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    mem_limit: 4g

volumes:
  mongo-data:
