# Use the official Node.js image based on Alpine Linux
FROM node:lts-alpine3.20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install server dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the Node.js server runs on
EXPOSE 3000

# Command to run the Node.js server
CMD ["node", "server.js"]